Add national_applicability to timeline table
The national_applicabilty column will store an array of UK nations.
I don't believe MySQL support array column types as Postgres does, so
instead we need to serialize the column [1]

The column will become a required field in later commits through the use
of validations in the model, but it has not been made required at the
database level for a few reasons:

1. Rubocop requires that not null columns need a default value:

db/migrate/20210702095110_add_national_applicability_to_coronavirus_timeline_entry.rb:3:81: C: Rails/NotNullColumn: Do not add a NOT NULL column without a default value.
    add_column :coronavirus_timeline_entries, :national_applicability, :string, null: false
                                                                                ^^^^^^^^^^^

This is a problem, as MySQL doesn't support arrays, so we need to set it
as a string, e.g. "england", but doing this causes the tests to fail
with:

ActiveRecord::SerializationTypeMismatch:
       can't dump `national_applicability`: was supposed to be a Array, but was a String. -- "england"

2. If we ignore the Rubocop requirement, then MySQL applies it's own
default which is an empty string. Rails doesn't understand that as an
array and throws an error:

```
irb(main):007:0> cte = Coronavirus::TimelineEntry.first Coronavirus::TimelineEntry Load (0.3ms) SELECT `coronavirus_timeline_entries`.* FROM `coronavirus_timeline_entries` ORDER BY `coronavirus_timeline_entries`.`id` ASC LIMIT 1 => #<Coronavirus::TimelineEntry id: 1, coronavirus_page_id: 1, content: "Test test", heading: "Test", position: 1, created_at: "20... irb(main):008:0> cte.national_applicability => "" irb(main):009:0> cte.save Traceback (most recent call last): 2: from (irb):9 1: from app/models/coronavirus/timeline_entry.rb:29:in `applies_to_uk_nations' NoMethodError (undefined method `each' for "":String) irb(main):010:0>
```

If you don't set `null: false` Rails will transparently translate a
value of null into an empty array, so you sidestep that problem and
don't have to write any code to handle a NULL value.

[1]: https://stackoverflow.com/questions/32409820/add-an-array-column-in-rails/32410318